### PR TITLE
Add example documentation

### PR DESCRIPTION
**Pull request by Gijsreyn**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-dsc).
- [ ] This pull request is related to an issue.

-----

This pull requests adds documentation examples for DSC modules.

### CODE REVIEW

**Comment by Gijsreyn** [comment]
@denelon Following up on PR #65 . I can indeed add other examples on the devhome, but I'm very much steering towards this repository. Bring everything together, that's my take on it. Let me know what you think.

**Comment by denelon** [comment]
I also think that would be best.

This is a great place for all things "WinGet Configuration" related. We can also refer to any of the DSC Community modules that might benefit from documentation for how to use them in WinGet Configurations.

I'd also like to be able to somehow "test" whether the experimental export configuration feature in WinGet works with a given resource or not.

**Comment by Gijsreyn** [comment]
Fully agreed Demitrius. Hit up Steve at the https://github.com/PowerShell/PSDesiredStateConfiguration/issues/123 to implement Export for PSDesiredStateConfiguration, or rely on DSC v3 I guess. We can also directly build the object in Pester tests do.

**Comment by denelon** [comment]
We did some work to make `winget configure export --module <a module> --resource <a resource>` instantiate a DSC Resource class to export the values. It's an experimental feature, and the last time I messed with it, mainly the WinGet user settings and admin settings were the only ones I was able to reliably export.

**Review by ryfu-msft — APPROVED** [review]

**Comment by Gijsreyn** [comment]
Thanks @ryfu-msft !

**Pull request merged**
