### PR TITLE
Windows settings language

### PR DESCRIPTION
**Pull request by Gijsreyn**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-dsc).
- [x] This pull request is related to an issue.

-----

Addresses the Microsoft.Windows.Setting.Language on #34 and #92.

> [!NOTE]  
> I recognize it has a bit more in the pull request (e.g. the `New-DscResourceModule` script). I added this script to help others get started and set standard information when a new module is introduced.

### CODE REVIEW

**Comment by Gijsreyn** [comment]
Hi @denelon and @stephengillie, I saw a pretty astonishing list on #34 so I thought of helping out. I didn't want to step on anyones toes, nor hijack any work. Hope you don't mind.

I've put the state to review. However, there are two TODOs in the module itself that raised some questions. You mind taking a look  and provide feedback? Thanks!

**Comment by stephengillie** [comment]
Hi @Gijsreyn,

Thank you for your help and sorry for the delay in responding. I'm dealing with capacity issues. 

This is a large change, adding and modifying numerous files, and modifies both documentation and code. Could the documentation changes be moved to another PR? That would make those changes more clear and easier to review, while allowing this PR to be focused on the DSC resource code.

**Comment by Gijsreyn** [comment]
@stephengillie No worries there. I think the tip from Josh on #89 to rebase shouldn't have it made that large. Sorry, have to upgrade my Git skills a bit. Always following to much of a standard approach on things. I'm closing this one and try to give it another shot.

**Comment by Trenly** [comment]
Another practice I've taken on is to set my git config to allow fast-forward only, that way only clean merges can happen. If a merge isn't clean, It will force me to either confirm that it can’t merge cleanly (using --no-ff) or I'll have to rebase

**Pull request closed without merging**
