### PR TITLE
Fix configuration file

### PR DESCRIPTION
**Pull request by Gijsreyn**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-dsc).
- [x] This pull request is related to an issue.

-----

Addresses issue #137 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-dsc/pull/138)

### CODE REVIEW

**Comment by Gijsreyn** [comment]
@Trenly and @ryfu-msft I think there was one small step missing in the configuration file inside this repository. This should fix it.

**Comment by Trenly** [comment]
> @Trenly and @ryfu-msft I think there was one small step missing in the configuration file inside this repository. This should fix it.

The configuration was built presuming the user was already operating inside the cloned repository, as would be the most common workflow when using DevHome

**Comment by Gijsreyn** [comment]
> > @Trenly and @ryfu-msft I think there was one small step missing in the configuration file inside this repository. This should fix it.
> 
> The configuration was built presuming the user was already operating inside the cloned repository, as would be the most common workflow when using DevHome

That was my assumption as well, but for fresh boxes, perhaps it is better to include it?

**Review by ryfu-msft — CHANGES_REQUESTED** [review]
I'd have to agree with Trenly here as well. In my mind the most common workflow would be to start by cloning this repo, then running `winget configure` on the configuration file. Your change will cause it to clone the same repo again. I think it is probably best to leave out the git clone part as that is not really needed within the context of this repo.

**Comment by Gijsreyn** [comment]
Thanks for the sharing and interesting thoughts. I would have assumed the GitClone resource would test for it. If it is already present, it applies the configuration successfully without additional cloning (depending on where the user executes it, of course). 

Regardless, I have removed the GitClone for now. I have fixed up the cloning because it was pointing towards winget-pkgs. I have added the PowerShell requirement.

**Review by ryfu-msft — APPROVED** [review]

**Pull request merged**
